plugins {
    id 'application'
}

application {
    mainClass = "eu.smink.ai.OllamaChatExample"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.testcontainers:ollama:1.21.3'
    implementation 'dev.langchain4j:langchain4j-core:1.1.0'
    implementation 'dev.langchain4j:langchain4j-ollama:1.1.0-rc1'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
}