plugins {
    id 'application'
}

application {
    mainClass = "eu.smink.ai.OllamaChatExample"
}

// Without the -parameter setting reflection does not know the method parameter names using reflection.
// As a result also the ToolSpecification of a tool with arguments will get "arg0" .. "argn" parameter names
// This fixed by adding the following code
tasks.withType(JavaCompile) {
    options.compilerArgs.add("-parameters")
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'dev.langchain4j:langchain4j-core:1.4.0'
    implementation 'dev.langchain4j:langchain4j-ollama:1.4.0'
    implementation 'dev.langchain4j:langchain4j-mcp:1.4.0-beta10'
    implementation 'io.modelcontextprotocol.sdk:mcp:0.12.1'
    implementation 'org.slf4j:slf4j-simple:2.0.17'
}